### ISSUE TITLE
Option to override context path of a web app via the deployment.yaml

### ISSUE THREAD

**Issue by this** [wso2/carbon-ui-server#47]
**Description:**
Currently context path of an app is computed by its name (`/ + name`) and there is no way to configure that. Customers should be able to change the context path of an app.

**Affected Product Version:**
v 0.12.5

**Comment by this** [comment]
sample `deployment.yaml`:

```yaml
...
wso2.carbon-ui-server:
    contextPaths:
        "portal": "my-dashboard"
        "monitor": "sys-status"
...
```
