### ISSUE TITLE
HTTP listener in case where HTTPS is forbidden?

### ISSUE THREAD

**Issue by mminks** [wso2/carbon-ui-server#75]
**Description:**

I'm wondering if it is still possible to deploy or configure the UI with a HTTP listener? I can find some hints that it should but no evidence so far. I live in an environment where HTTPS is a problem. A workaround would be to fake things that the UI accepts a login from a non-secure client. Because that's the main problem. The UI denies a login from HTTP.

Nevertheless, SSL termination at an earlier point in the infrastructure would be much better and easier to handle. I prefer to outsource SSL termination to a central place so all services would benefit from it.

**Affected Product Version:**

Stream Processor Status Dashboard 4.3.0

**Steps to reproduce:**

```
wso2.transport.http:
  transportProperties:
    - name: "server.bootstrap.socket.timeout"
      value: 60
    - name: "client.bootstrap.socket.timeout"
      value: 60
    - name: "latency.metrics.enabled"
      value: true

  listenerConfigurations:
    - id: "default-https"
      host: "0.0.0.0"
      port: 9643
      scheme: https
      keyStoreFile: "${carbon.home}/resources/security/wso2carbon.jks"
      keyStorePassword: wso2carbon
      certPass: wso2carbon
```

Changing things to something like this

```
  listenerConfigurations:
    - id: "default-https"
      host: "0.0.0.0"
      port: 9643
      scheme: https
```
doesn't work.

```
Caused by: org.wso2.carbon.uiserver.internal.exception.AppDeploymentEventListenerException: Cannot find any HTTPS transports to register web app 'portal'.
```

**Related Issues:**

https://github.com/wso2/carbon-ui-server/issues/33

**Comment by this** [comment]
@mminks I'm not sure whether I understood your requirement correctly.
What you want is to disable HTTPS for a webapp, then it can be done by configuring a HTTP `listenerConfiguration` in the `deploymet.yaml` and configuring that to be used for your webapp.

e.g. `deploymet.yaml`
```yaml

# Carbon UI server configurations
wso2.carbon-ui-server:
  apps:
    # configurations for the Portal app
    "portal":
      transportId: "for-portal-app"

# HTTP transport related configurations
wso2.transport.http:
  transportProperties:
    - name: "server.bootstrap.socket.timeout"
      value: 60
    - name: "client.bootstrap.socket.timeout"
      value: 60
    - name: "latency.metrics.enabled"
      value: true

  listenerConfigurations:
   # HTTP transport for the Portal web app
    - id: "for-portal-app"
      host: "0.0.0.0"
      port: 9090

  senderConfigurations:
    - id: "default-http-sender"

```
You can refer the Documentation section of PR #64 for more details.
